version: '3'

services:
        db:
          image: mysql
          container_name: app-db
          command: --default-authentication-plugin=mysql_native_password
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: example
          ports:
            - 3306:3306
          expose:
            - 3306
          volumes:
            - ./db/data:/var/lib/mysql:rw
            - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
