version: '3'

services:

      app:
        build:
          context: ./app
        container_name: app-web
        volumes:
          - "../:/var/www/app"
        links:
          - db
        depends_on:
          - db
        ports:
          - 80
        network_mode: "bridge"

      db:
        image: mysql
        container_name: app-db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
          - MYSQL_DATABASE=test_db
        ports:
          - 3306:3306
        expose:
          - 3306
        volumes:
          - ./db/conf.d:/etc/mysql/conf.d:rw
          - ./db/data:/var/lib/mysql:rw
          - ./db/schema:/schema:ro
        network_mode: "bridge"
